"""add hit_count

Revision ID: 1234567890ab
Revises: a1b2c3d4e5f6
Create Date: 2026-05-14 21:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1234567890ab'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_human_session', sa.Column('hit_count', sa.Integer(), nullable=True))
    op.execute("UPDATE task_human_session SET hit_count = 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_human_session', 'hit_count')
    # ### end Alembic commands ###
